***********************************
Punto de venta
***********************************

--Creo USUARIO: administrador con sus permisos y tablas

CREATE USER ADMINISTRADOR IDENTIFIED BY ADMIN_1;

GRANT ALL PRIVILEGES TO ADMINISTRADOR;

-- TABLA 

CREATE TABLE ADMINISTRADOR
(ID_ADMINISTRADOR NUMBER(5),
NOMBRE VARCHAR2(20),
APELLIDO_P VARCHAR2(20),
APELLIDO_M VARCHAR2(20),
EMAIL VARCHAR2(40),
TELEFONO NUMBER(15),
CONTRASENIA VARCHAR(6)
);

ALTER TABLE AMINISTRADOR
ADD CONSTRAINT administrador_idadmin_pk
PRIMARY KEY(ID_ADMINISTRADOR);

ALTER TABLE AMINISTRADOR
MODIFY NOMBRE VARCHAR2 NOT NULL; 

ALTER TABLE AMINISTRADOR
MODIFY APELLIDO_P VARCHAR2 NOT NULL; 

ALTER TABLE AMINISTRADOR
MODIFY APELLIDO_M VARCHAR2 NOT NULL; 

ALTER TABLE AMINISTRADOR
ADD CONSTRAINT email_uq
UNIQUE(EMAIL);

ALTER TABLE AMINISTRADOR
ADD CONSTRAINT telefono_uq
UNIQUE(TELEFONO);

ALTER TABLE AMINISTRADOR
MODIFY CONTRASENIA VARCHAR2 NOT NULL; 


-- TABLA 

CREATE TABLE VENTAS
(ID_VENTA NUMBER(10),
ID_ADMINISTRADOR NUMBER(5),
ID_VENDEDOR NUMBER(5),
IVA NUMBER(4,2)
);

ALTER TABLE VENTAS
ADD CONSTRAINT ventas_idventa_pk
PRIMARY KEY(ID_VENTA);

ALTER TABLE VENTAS 
ADD CONSTRAINT ventas_idadmin_fk
FOREIGN KEY(ID_ADMINISTRADOR)
REFERENCES ADMINISTRADOR((ID_ADMINISTRADOR);

***** CREAR ROLE PARA PODER HACER LA FK

ALTER TABLE VENTAS 
ADD CONSTRAINT ventas_idvendedor_fk
FOREIGN KEY(ID_VENDEDOR)
REFERENCES VENDEDOR((ID_VENDEDOR);

-- TABLA 

CREATE TABLE REPORTE_VENTAS
(ID_REPORTEVENTAS NUMBER(5),
ID_VENTA NUMBER(10),
FECHA_REPORTE SYSDATE,
GANANCIA_TOTAL NUMBER(15)
);

ALTER TABLE REPORTE_VENTAS
ADD CONSTRAINT reporte_ventas_idreporte_pk
PRIMARY KEY(ID_REPORTEVENTAS);

ALTER TABLE REPORTE_VENTAS
ADD CONSTRAINT reporte_ventas_idventa_fk
FOREIGN KEY(ID_VENTA)
REFERENCES VENTAS((ID_VENTA);

-- TABLA 

CREATE TABLE PRODUCTO
(ID_PRODUCTO NUMBER(10),
NOMBRE VARCHAR2(30),
MARCA VARCHAR2(20),
CATEGORIA VARCHAR2(20),
PRECIO NUMBER(4),
IEPS NUMBER(4,2),
CANTIDAD NUMBER(5)
);

ALTER TABLE PRODUCTO
ADD CONSTRAINT producto_idproducto_pk
PRIMARY KEY(ID_PRODUCTO);

-- TABLA 

CREATE TABLE DETALLE_VENTAS
(ID_DETALLEVENTAS NUMBER(10),
ID_VENTA NUMBER(10),
ID_PRODUCTO NUMBER(10),
FECHA SYSDATE,
TIPO DE PAGO VARCHAR2(10),
GANANCIA_TOTAL NUMBER(15)
);

ALTER TABLE DETALLE_VENTAS
ADD CONSTRAINT detallev_iddetallev_pk
PRIMARY KEY(ID_DETALLEVENTAS);

ALTER TABLE DETALLE_VENTAS
ADD CONSTRAINT detallev_idventa_fk
FOREIGN KEY(ID_VENTA)
REFERENCES VENTAS(ID_VENTA);

ALTER TABLE DETALLE_VENTAS
ADD CONSTRAINT detallev_idproducto_fk
FOREIGN KEY(ID_PRODUCTO)
REFERENCES PRODUCTO(ID_PRODUCTO);


-- TABLA 

CREATE TABLE TICKET
(ID_TICKET NUMBER(10),
ID_DETALLEVENTAS NUMBER(10),
ID_VENTA NUMBER(10)
);

ALTER TABLE TICKET
ADD CONSTRAINT ticket_idticket_pk
PRIMARY KEY(ID_TICKET);

ALTER TABLE TICKET
ADD CONSTRAINT ticket_iddetallev_fk
FOREIGN KEY(ID_DETALLEVENTAS)
REFERENCES DETALLE_VENTAS(ID_DETALLEVENTAS);

-- TABLA 

CREATE TABLE FACTURA
(ID_FACTURA NUMBER(10),
USOCFDI NUMBER(10),
ID_DETALLEVENTAS NUMBER(10),
ID_VENTA NUMBER(10)
);

ALTER TABLE FACTURA
ADD CONSTRAINT factura_idfactura_pk
PRIMARY KEY(ID_FACTURA);

ALTER TABLE FACTURA
ADD CONSTRAINT factura_iddetallev_fk
FOREIGN KEY(ID_DETALLEVENTAS)
REFERENCES DETALLE_VENTAS(ID_DETALLEVENTAS);

-- TABLA 

CREATE TABLE CLIENTE
(ID_CLIENTE NUMBER(10),
ID_TICKET NUMBER(10),
ID_FACTURA NUMBER(10)
);

ALTER TABLE CLIENTE
ADD CONSTRAINT cliente_idcliente_pk
PRIMARY KEY(ID_CLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT cliente_idticket_fk
FOREIGN KEY(ID_TICKET)
REFERENCES TICKET(ID_TICKET);

ALTER TABLE CLIENTE
ADD CONSTRAINT cliente_idfactura_fk
FOREIGN KEY(ID_FACTURA)
REFERENCES FACTURA(ID_FACTURA);

-- TABLA 

CREATE TABLE VENDEDOR
(ID_VENDEDOR NUMBER(5),
NOMBRE VARCHAR2(20),
APELLIDO_P VARCHAR2(20),
APELLIDO_M VARCHAR2(20),
EMAIL VARCHAR2(40),
TELEFONO NUMBER(15),
CONTRASENIA VARCHAR(6)
);

ALTER TABLE VENDEDOR
ADD CONSTRAINT cliente_idcliente_pk
PRIMARY KEY(ID_CLIENTE);


--Creo USUARIO: vendedor con sus permisos y tablas

CREATE USER VENDEDOR IDENTIFIED BY VENDEDOR;

GRANT CREATE SESSION TO VENDEDOR;







